name: Trigger Target Workflow

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          repo_owner="LabVIEWCommunityTraining"
          repo_name="www"
          workflow_file="publish-website-on-gh-pages.yml"
          branch="main"
          json_data="{\"ref\": \"$branch\"}"
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.WEBSITE_DELIVERY_TRIGGER }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$repo_owner/$repo_name/actions/workflows/$workflow_file/dispatches \
          -d "$json_data"
