name: Trigger Target Workflow

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          repo_owner="LabVIEWCommunityTraining"
          repo_name="www"
          workflow_file="publish-website-on-gh-pages.yml"
          branch="main"
          json_data="{\"ref\": \"$branch\"}"
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.WEBSITE_DELIVERY_TRIGGER }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$repo_owner/$repo_name/actions/workflows/$workflow_file/dispatches \
          -d "$json_data"

  publish_zip:
      runs-on: ubuntu-latest
      needs: []  # Run in parallel
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Zip course-material
          run: |
            cd course-material
            zip -r ../course-material.zip . 
            cd ..

        - name: Move zip to _public folder
          run: |
            mkdir -p _public
            mv course-material.zip _public/

        # download UIs
        - name: Upload GitHub Pages Artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: _public
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4